### PR TITLE
Add search component binding to skip over search button while tabbing

### PR DESCRIPTION
**Pull request by Blackbaud-LukeJones**

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: bedb95dbc3a6ec3717d6a5c483bba8d5cc18f810
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/272490780

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-LukeJones** [comment]
I've added this functionality to another component as well, so I'm going to close this request and file another with all the changes.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 9f95a4b2dc07c295c733385edd095e544b9d643c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/272949720

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 139c64a9ecaeeff38ecda984097a82fcbe80a7a7
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/272949881

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request closed without merging**
