### PR TITLE
Grunt + config reorg

### PR DESCRIPTION
**Pull request by Blackbaud-BobbyEarl**
What started as an effort to allow visual tests to locally run against browserstack, turned into a complete reorganization of the massive `gruntfile.js`.  Most of the the grunt tasks remain untouched, only grouped into separate files organized by process.  The folllowing additions are important to note.
- Removed `watchrapid`, `scriptsrapid`, and `stylesrapid` tasks.  Instead the `watch`, `build`, `scripts`, and `styles` tasks will honor a `--rapid` flag.
- Created separate tasks for `unittest` and `visualtest`, both of which honor the `--browserstack` flag.  If specified, a `browserstack.env` file must also exist (it will be automatically loaded) which should look like the following:

```
BROWSER_STACK_USERNAME="<username-from-browserstack-website>"
BROWSER_STACK_ACCESS_KEY="<access-key-from-browserstack-website>"
```
- The environment is still automatically determined, but can be overridden using the `--env=` option, passing in a valid value from the `env.SUPPORTED` object.  For example, `grunt test --env=ci-pullrequest-fork`
- Last, is a more efficient `watch` task and automatic serving of the docs (including livereload).  When running `grunt watch` you can now visit [http://localhost:4000](http://localhost:4000).  As an example of more efficient watching, changing one of the markdown files will cause the docs to update, but not perform a build.  Please note, this functionality requires the version 0.7.15 of Stache because of https://github.com/blackbaud/stache/issues/53

### CODE REVIEW

**Comment by Blackbaud-PaulCrowder** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/430/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Comment by Blackbaud-PatrickOFriel** [comment]
Is there a reason the wdio.conf-local-browserstack includes more browsers than our Travis visual tests?

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-PatrickOFriel I added those as tests.  Also nice to have them configured so we can run them one-off.  I can definitely remove if we don't want to have those configured.

**Comment by Blackbaud-PatrickOFriel** [comment]
Fine with me, just curious if they were working in under 30 minutes with IE?

**Pull request merged**
