### PR TITLE
GitHub folder issue template

### PR DESCRIPTION
**Pull request by Blackbaud-PaulCrowder**

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
Approve

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/336/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
