### PR TITLE
Simplify code around vertical tabset tab template.

### PR DESCRIPTION
**Pull request by Blackbaud-BenCook**
I realized that the `sky/templates/tabset/verticaltabsettab.html` template is unnecessary as it only impacts styling, and these styles can be achieved via SCSS changes alone. This PR removes unneeded code. 

It will also make the vertical tabset more compatible when consumers attempt to transclude content that is compiled before it is inserted into the DOM, such as the following: `<uib-tab ng-repeat"foo in foos"></uib-tab>`. In the case of such content, the vertical tabset component does not correctly determine which template to use. By removing the conditional logic around the template altogether, this PR makes the component more flexible.

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 42f766684199aa4b8d5e5bed6dd3ef0b083e3fd6
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/231224123

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 42f766684199aa4b8d5e5bed6dd3ef0b083e3fd6
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/231299475

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
Looks like the existing vertical tab visual regression tests are failing. Is that intended?

**Comment by blcook223** [comment]
No, these are the screenshot diffs I'm getting locally. They are very small, but I haven't yet figure out why they would be different at all.

mac_chrome_vertical_tabset_group_full vertical_tabset_group 1280px baseline
mac_chrome_vertical_tabset_group_inactive_full vertical_tabset_group_inactive 1280px baseline
mac_chrome_vertical_tabset_no_group_full vertical_tabset_no_group 1280px baseline
mac_chrome_vertical_tabset_no_group_inactive_full vertical_tabset_no_group_inactive 1280px baseline

**Comment by Blackbaud-PatrickOFriel** [comment]
Well, if @Blackbaud-ToddRoberts or another designer can verify that the vertical tabs look acceptable, we can accept the pixel difference as a result of changing from using the template to css and delete the screenshots to create a new baseline

**Comment by Blackbaud-ToddRoberts** [comment]
Can I get a straight up side by side of old vs new? It's hard to tell what's going on with the magenta lines.

**Comment by Blackbaud-PatrickOFriel** [comment]
When I update this pull request with the latest I'll show grab the old and new screenshots side by side for you @Blackbaud-ToddRoberts

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 3aa7b423312cf2ac2686326718ca998f00bc1a4b
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/231605485

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-ToddRoberts 
Here's the old: https://raw.githubusercontent.com/blackbaud/skyux-visualtest-results/179-webdriver-savage/reference/webdriver-screenshots/MAC_chrome/MAC_chrome_vertical_tabset_group_full.vertical_tabset_group.1280px.baseline.png

Here's the new: https://raw.githubusercontent.com/blackbaud/skyux-visualtest-results/179-webdriver-savage/created-screenshots/webdriver-screenshots-screen/MAC_chrome/MAC_chrome_vertical_tabset_group_full.vertical_tabset_group.1280px.baseline.png

**Comment by Blackbaud-ToddRoberts** [comment]
Based on that it seems fine

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: f2ee5c71136ff76acf0175a005496c9873a1ee8d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/231645543

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-BenCook looks like github thinks you have some conflicts with the screenshots, any reason why?

**Comment by Blackbaud-BenCook** [comment]
@Blackbaud-PatrickOFriel, I guess those screenshots were modified on the master branch somewhere. I've merged master into my branch now and removed the screenshots so they will get regenerated.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 8cad7e127d5b9b29f1b46d6833cdd60d0313b169
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/232556784

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request merged**
