### PR TITLE
Add a `columnsResized` event that can be used for persisting column s…

### PR DESCRIPTION
**Pull request by Blackbaud-IanThomas**
…ize changes in a controller #366

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: e12d9474da7250eae80dcbeec8e56f679f3e574c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/112942873

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
A couple things: I saw in the `resizeStop` function there's a return within an if statement, which means that your event won't be emitted in that case, so we might have to rework the `resizeStop` function. Also, how do you grab column size after this event occurs?

**Comment by Blackbaud-IanThomas** [comment]
Good point.  I actually was just noticing the first part myself in testing.  It will trigger the event if I shrink a column, but it will not trigger it the first time I expand and column when there is an extended column present.  I'll make that event trigger inside that if, as well. In your opinion, does that require another test?

I didn't want to add a bunch of junk to the grid, so I'm grabbing the column widths via jQuery inside my controller. My first goal was to find the widths of columns in the scope somewhere, but it seems like that transient information isn't tracked anywhere but the style attribute of the header row. A cleaner way to accomplish this that doesn't add that calculation overhead to the grid would be very welcome.

**Comment by Blackbaud-PatrickOFriel** [comment]
It either requires another test, or we should rework that if statement so it doesn't return in the middle of the function. Let me think about if there's a clean way to grab the column width info.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hokay, there's a way to get the jqgrid column model, which should have the current width (if I'm reading their crazy documentation right. In the `resizeStop` function, you should be able to do `var currentColumns = tableEl.getGridParam('colModel')`. And then you can access width using `currentColumns[0].width, currentColumns[1].width, etc`. So it might be worthwhile to send that columnModel up with the width. @Blackbaud-PaulCrowder @Blackbaud-BobbyEarl, what do you think?

**Comment by Blackbaud-BobbyEarl** [comment]
Do we need to send up the entire model?  The jqGrid resizeStop event we're already tapped into gives us the new width and index.

**Comment by Blackbaud-PatrickOFriel** [comment]
So the resizeStop event can make the last column become shorter in some cases. So I would assume they might want that information. If they don't care about the size of that extended column then yes, they can just pass up that newWidth. They might also have to adjust the index given there to account for context menu/multiselect columns

**Comment by Blackbaud-IanThomas** [comment]
Thanks, guys. I really like this discussion.  My first inclination as I've been doing this work was to save the state of _all_ columns, but thinking about it as you guys have discussed it makes me think that all I need to do is save the columns that differ from default. If that were the case, all I need is the column information that @Blackbaud-BobbyEarl mentioned.  I'm still in the middle of implementing the behavior within eTap, and this should nicely simplify some of the code I was writing.  I'll give that a shot and update my pull request.  Any objections to triggering the event at the top of `resizeStop` for the sake of not messing around with the return within the if?

I had one more question that's been slowing me down today.  Maybe your familiarity with the grid will make it easier on me.  When I've saved this customized width, whenever I reload the grid, I'm currently setting the `width_all` property of the column model to the customized width. That works fine, unless I want to "un-customize" it on the page (we have a restore defaults button).  I can change the model back to the default width, but it doesn't do anything unless I trigger a `reinitGrid()`, which I can't do manually.

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah I think triggering at the top should work since you don't really care about that extended column. 

As for the grid initialization, looking now there's not a real intuitive way to do this (no property initGrid that you can set to true to trigger it). Changing options.selectedColumnIds should do the trick, but it might be worth providing a hook that can do so.

**Comment by Blackbaud-IanThomas** [comment]
I made the change to trigger the event at the top and pass the worthwhile column information.

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 234245fe4476ca0e01e0c83a80b47d387555e6d4
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/112980879

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 234245fe4476ca0e01e0c83a80b47d387555e6d4
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/113125727

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Couple documentation notes, you have a stray 'w' in the word 'Fires'. Also, you might want to mention what values get passed along with the event. Something like: 

Fires when the columns have finished resizing on the page.  You can use this event to listen for column size changes and save them for subsequent visits to the grid. Event contains an object with the following properties: 
- `index` &mdash; the index of the resized column
- `newWidth` &mdash; the new width of the resized column

Last note: You have to subtract 1 from that index if there is a multiselect column, and you have to subtract 1 from that index if there is a context menu column. Pretty much the opposite of what's going on around line 341 in grids.js

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 867a9914040dc841af8859dfaff8a80fce86a185
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/113172273

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 40027587d46243c3c513bac9fc5fc0d32c2e4b62
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/113172818

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/367/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
