### PR TITLE
Fix palette demo

### LINKED ISSUE #246: Palette demo example is incorrect
The [palette demo](http://skyux.developer.blackbaud.com/components/palette/) has an example showing the 7th color in the palette. The palette is zero-based, but the example shows the color at index 7, so the example is incorrect.

### PR DESCRIPTION
**Pull request by Blackbaud-ChristiSchneider**
Fixes #246

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 444d5ef2994fe192fd31444d4cd0f4da08808178
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/105232084

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 444d5ef2994fe192fd31444d4cd0f4da08808178
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/105249006

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PaulCrowder** [comment]
The build failure was not due to Christi's change so it was safe to merge.

**Pull request merged**
