### PR TITLE
Add codecov instead of coveralls

### PR DESCRIPTION
**Pull request by Blackbaud-PatrickOFriel**

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
Waiting to merge this until the next version of codecov is released to fix https://github.com/codecov/support/issues/214

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-PatrickOFriel did you mention this was ready now?

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-BobbyEarl yes

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/586/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
