### PR TITLE
Correct scrollbars on sectioned form

### PR DESCRIPTION
**Pull request by Blackbaud-MatthewBell**
Move to using flex box styling for the nav tabs and tab content.
Updating to use padding at top of tab-content to avoid creating a
vertical scrollbar.

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 12959545a11aa7f2de55fb7959ff7fa2f6809edc
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/215584291

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: d3f49891e033822c5778a0cae1b29195bff98236
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/215584295

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-MatthewBell You'll have to delete the sectionedform screenshots for chrome and firefox in https://github.com/blackbaud/skyux/tree/master/webdriver-screenshots for them to update properly. Also, where's the vertical scrollbar issue coming into play? I know moving to flex fixes the horizontal scrollbar for the heading section.

**Comment by Blackbaud-PatrickOFriel** [comment]
Also looking at the before https://github.com/blackbaud/skyux-visualtest-results/blob/164-webdriver-savage/reference/webdriver-screenshots/MAC_chrome/MAC_chrome_sectionedform_full.sectionedform.1280px.baseline.png, and after screenshots https://github.com/blackbaud/skyux-visualtest-results/blob/164-webdriver-savage/created-screenshots/webdriver-screenshots-screen/MAC_chrome/MAC_chrome_sectionedform_full.sectionedform.1280px.baseline.png, looks like the content area doesn't have the correct width anymore after that change. That's what's causing the visual test failure. Maybe need to do a flex grow/flex shrink somewhere?

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 737d0a1ee5fa83d1f8d1056b552c62a86649f6cd
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/215675547

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: e0842a94141bd613c9961e6d573aee009d10252b
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/216017284

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
#1005

**Pull request merged**
