### PR TITLE
Updated search box to respect full width property

### PR DESCRIPTION
**Pull request by blackbaud-GavinNicol**
This addresses: https://github.com/blackbaud/skyux/issues/1097

### CODE REVIEW

**Comment by blackbaud-GavinNicol** [comment]
#1097

**Comment by blackbaud-GavinNicol** [comment]
Plunker of working example: http://plnkr.co/edit/vxN78pUuS6AD9fApFoxP?p=preview

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 702c4c51b5dbbf277a611bb482c269fed0c0e406
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/443762265

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 702c4c51b5dbbf277a611bb482c269fed0c0e406
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/445813468

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-GavinNicol** [comment]
@blackbaud-sky-savage retry

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 702c4c51b5dbbf277a611bb482c269fed0c0e406
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/446816196

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 702c4c51b5dbbf277a611bb482c269fed0c0e406
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/449344105

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 702c4c51b5dbbf277a611bb482c269fed0c0e406
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/451406937

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 702c4c51b5dbbf277a611bb482c269fed0c0e406
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/451417856

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Review by Blackbaud-BobbyEarl — APPROVED** [review]

**Pull request merged**
