### PR TITLE
Percent preset for bb autonumeric

### PR DESCRIPTION
**Pull request by Blackbaud-MichaelLopez**

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 461903b12141f833b22fd1b9e29017d7f35a468a
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/119929355

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Should percent always have 2 decimal places?

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: f164f4b9063b5103a9a01144ebd2102bf7060dab
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/120055877

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-MichaelLopez** [comment]
Yea not sure what you guys think. In the example of autonumeric's demo page there are decimals.

**Comment by Blackbaud-PatrickOFriel** [comment]
I like having no decimals by default and letting the user pass in the ability to have decimals using the autonumeric enhancement you made last month. How about you @Blackbaud-ToddRoberts @Blackbaud-PaulCrowder ?

**Comment by Blackbaud-ToddRoberts** [comment]
my preference is for no decimals by default, as long as it's possible to opt in to including decimals even out to 4 places (FE uses them to that precision).

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-MichaelLopez if you change this to do no decimals by default, as long as it can be overridable I think we'll be good to go.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: ae54e3405aad925469c07168ac4d0278b4a2cc1d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/122517107

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/442/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
