### PR TITLE
Pull dependencies from npm instead of bower

### PR DESCRIPTION
**Pull request by Blackbaud-BethRichardson**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 634e6b641bf37f971e8ccb86956c8101941acdda
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/130080843

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6fa77ea358a8ec8dcb305c271b699b7be87d2dbb
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/130591797

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6fa77ea358a8ec8dcb305c271b699b7be87d2dbb
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/130660139

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-BethRichardson Switching the npm version of angular-ui-select back to the currently specified version of 0.11.2 (versus 0.13.2 in your PR) fixed the remaining two visual regression errors in my local testing.  Was there a cause to upgrade?

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: f7b010c19e029b93fcd9a2508561901afd372777
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/130712609

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-BobbyEarl** [comment]
As determined, @Blackbaud-BethRichardson upgraded ui-select to from version 0.11.2 to 0.13.2.  The reason for doing so, is until the 0.13.0 release, the ui-select npm package runs `bower install` on a postinstall process.  This is a problem for us as we don't run `npm install -g bower` until the `before_script` step in `.travis.yml` so bower isn't available yet.

Unfortunately, as pointed out above, upgrading the version of ui-select selects the [second item](https://raw.githubusercontent.com/blackbaud/skyux-visualtest-results/74-webdriver-savage/all/webdriver-screenshots/MAC_firefox/MAC_firefox_searchfield_single_dropdown_full.searchfield_single_dropdown.1280px.regression.png) instead of the [first item](https://raw.githubusercontent.com/blackbaud/skyux-visualtest-results/74-webdriver-savage/all/webdriver-screenshots/MAC_firefox/MAC_firefox_searchfield_single_dropdown_full.searchfield_single_dropdown.1280px.baseline.png), in our [visual regression test](https://github.com/blackbaud/skyux/blob/master/webdrivertest/test/searchfield/searchfield.visual.js#L46).  I believe we have a few options:
1. Move the `npm install -g bower` to the `before_script` step in `.travis.yml` so that bower is available before `npm install` is called.
2.  Make sure there are no negative side effects and allow the upgrade to 0.13.2 (remove screenshots).
3.  Since we've already deprecated ui-select, remove it completely in this PR.
4.  Submit this PR against the upcoming 1.6.0 release, since ui-select has already been removed there.

What say you @Blackbaud-PaulCrowder and @Blackbaud-PatrickOFriel ?

**Comment by Blackbaud-PatrickOFriel** [comment]
I'm for option 2 or 4.

**Comment by Blackbaud-BethRichardson** [comment]
Option 2 is best for us but I am flexible for the other options if that works better for your team.

**Comment by Blackbaud-PaulCrowder** [comment]
I like option 4.  We're planning on removing that component, so I'd prefer not to spend much time on it.  We can go ahead and release 1.6.0.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hokay, ley's do one more release of the stuff put into 1.5.x since last release, and then merge that into rc-1.6.0, and then we can merge rc-1.6.0 into master and put the npm changes in there. I can take that on tomorrow morning.

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6abd84a6549050bffcae1b5113c69b4bb9e77d52
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/131238196

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6abd84a6549050bffcae1b5113c69b4bb9e77d52
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/131246518

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 6abd84a6549050bffcae1b5113c69b4bb9e77d52
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/131252769

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/570/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
