### PR TITLE
Bb datepicker calendar click

### PR DESCRIPTION
**Pull request by Blackbaud-PatrickOFriel**

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
This is the custom validation updates for the 1.5.x branch

**Comment by Blackbaud-BobbyEarl** [comment]
Seeing the following in the dev console in Chrome.  Is it intended / acceptable behavior?

screen shot 2016-05-02 at 10 10 41 am

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah that's already a problem on blur in chrome in the current version of custom validation. It's fixed in 1.6.x, with the ui-bootstrap datepicker updates.

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/544/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
