### PR TITLE
Add an index.js and reference it as the main from package.json so we …

### PR DESCRIPTION
**Pull request by Blackbaud-JasonBilyeu**
…can pull sky in through commonJS.

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-JasonBilyeu, just curious, what is the change/requirement which needs this functionality?

**Comment by Blackbaud-BobbyEarl** [comment]
Additionally, @Blackbaud-JasonBilyeu In order to successfully run the test suite, please [sign the CLA](https://cla-assistant.io/blackbaud/skyux?pullRequest=608) (as linked above) and follow [these instructions](https://help.github.com/articles/publicizing-or-hiding-organization-membership/) to make yourself a public member of the Blackbaud organization.

**Comment by Blackbaud-JasonBilyeu** [comment]
@Blackbaud-PatrickOFriel - These changes are necessary to consume sky through a CommonJS loader (including a few small fixes to get it to work).  One caveat of the index.js is going forward any additions/deletions of dependencies to sky will need to be added here as well.  Logged issue with reasons why we have to do this for now: https://github.com/blackbaud/skyux/issues/609

@Blackbaud-BobbyEarl - I signed the CLA and made myself a public member of the Blackbaud organization.

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 76b582a2b61b07d5e487e073ceebed72de2ecd39
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/136257130

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 76b582a2b61b07d5e487e073ceebed72de2ecd39
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/136264067

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PaulCrowder** [comment]
Given that you've already filed a bug against the contents of this pull request I feel like this is a potential rabbit hole that we'd rather not go down at this time.  Perhaps if you could give a little more context (I know that you want to use a CommonJS loader, but what CommonJS loader?  Why use a CommonJS loader?  Why does the existing `sky-bundle.js` file work for other projects but not for yours?  Or does it not work for other projects as well?) then maybe we can make a better assessment on whether we spend time implementing this and tracking down the issues it could introduce.

**Comment by Blackbaud-JasonBilyeu** [comment]
The bug is not against the contents of this PR.  The bug is related to the way momentjs is included in sky libs.js in that moment refers to './locale/' folder that exists in their project but not in the dist/js folder.  I believe that means that if anyone tries to use moment locale functionality in skyux it would not work.

This PR is necessary for us to import blackbaud-skyux from ES6 javascript.  For example, we are trying to do this:  `import * as sky from 'blackbaud-skyux';`.  The import will not work without this PR as blackbaud-skyux package.json does not include a 'main' entrypoint.  After we added a main entrypoint ('index.js'), we discovered a few pre-existing issues.  We fixed the two easy ones as part of this PR, but deferred fixing the moment bundling issue and manually included all libs instead in this PR's index.js.

This will satisfy our needs for now, and once the issue is resolved this index.js can be simplified to just require 'sky-bundle'.

**Comment by Blackbaud-PaulCrowder** [comment]
How are you adding SKY UX to your project today without this change?  Could you not just create this `index.js` file locally in your project and then import it?  Or are you already doing that and you made this change so others could benefit from it?

**Comment by Blackbaud-RobertTester** [comment]
Is there something wrong with proposed change?  It looks like Jason's change is just making the blackbaud-skyux npm package follow standards and fixing existing bugs in skyux.  If you disagree please explain.  

This change should benefit anyone that wants to use a CommonJS module loader to bring in SkyUX to their project.  Without this change it will simply not work in that context.

**Comment by Blackbaud-PaulCrowder** [comment]
It's not that there's something wrong with this particular change, but as with any change it involves risk.  We're just trying to mitigate risk by fully understanding the scope of the change, the motivation behind it, what the SKY UX team needs to do going forward to maintain this change, how we test that we don't break it in future releases, how we document it, how we advise other teams on using it, etc.

**Comment by Blackbaud-RobertTester** [comment]
The motivation behind the change is to allow a CommonJS loader (i.e. webpack) to consume skyux.  All changes proposed in this change will have no impact on applications including the library in their browser directly.  I doubt anyone is currently doing this because it will not work in its current state.

The implication for the SkyUX team would be that they need to update the index.js file with anhy dependency changes.  We can avoid this by including the sky-bundle.js inside of the index.js but the published directory does not contain the locales folder that moment looks for.  If we add this directory to the dist folder than we could do this.

Let me know what additional information you would like from us about this change.  If you want us to fix the moment issue we can do that as well.

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-RobertTester, why were the changes in data and mediabreakpoints necessary? Was there some sort of breakage happening when keeping them the original way?

**Comment by Blackbaud-RobertTester** [comment]
@Blackbaud-PatrickOFriel 

The change to data was to be more explicit about the require function being used.  We added $window before the require call to make sure that it did not get confused with the require module loader function.  This should be safe because the if statement to get to this code checks for $window.require.    

The change to mediabreakpoints is to fix a bug.  There is no enquire package present.  There is only enquire.js.  

Let me know if that answers your question.

**Comment by Blackbaud-PaulCrowder** [comment]
@Blackbaud-JasonBilyeu Can check the size of `sky-bundle.js` or `libs.js` before and after you included the moment locale files?  Since they're not currently being included I want to make sure including them doesn't add too much to the overall bundle size.

**Comment by Blackbaud-PatrickOFriel** [comment]
Makes sense @Blackbaud-RobertTester, thanks!

**Comment by Blackbaud-JasonBilyeu** [comment]
@Blackbaud-PaulCrowder We didn't include the locale directory from moment as part of this PR.  We could do that and simplify the index.js as part of this PR if you want?  That would be the fix for https://github.com/blackbaud/skyux/issues/609.

**Comment by Blackbaud-PaulCrowder** [comment]
But does requiring moment in this PR not then pull in the locale files through its own `require()` call?  I just want to verify whether that happens and if it does how it affects the overall file size of the bundled `sky-bundle.js` and `libs.js` files.

**Comment by Blackbaud-JasonBilyeu** [comment]
No, requiring moment in the index.js simply loads up moment in memory.  It does not modify the `sky-bundle.js` or `libs.js` files as they are already created when an application uses the index.js to load sky.

Does that make sense, or am I missing something?

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7f8f95b2eee1ad5b79eba9ee3e9e40d6b1e48d15
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/136757065

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-JasonBilyeu** [comment]
This PR now fixes https://github.com/blackbaud/skyux/issues/609 as we are now including the moment locale folder in the dist/js folder.  Please let us know if you have any further questions.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: d9ea8faf7f10794358ac73a00f0093c7a1993422
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/140082487

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 508a5da38ec024ccb353476fb782fa6a3db4cf6a
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/140097981

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: cd50b2e923064739b9e7d165ff2d018d799dcff4
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/140101348

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 39ad98933b2f61636e2fc07692757e8ae3347758
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/140102872

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Pull request closed without merging**
