### PR TITLE
Updates from John L edits plus adding fieldset and legend to check demo html

### PR DESCRIPTION
**Pull request by Blackbaud-MattGregg**
Using the legend element seemed to bring a specific style that is declared for at the legend element. Just an fyi. I'm not sure if all "legends" in SKY UX are meant to get that style (large font size + bottom border)

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: f01ffdec190e56e611ea880a5f89a674c30aa95e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/186194158

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 2a456b372439a63dd30e50b0137397d2b747cc5f
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/190631888

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 6fe8e864a615cf1ea58ba6fc62ddb642b439ff06
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/191366189

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
Digging into this @Blackbaud-PatrickOFriel, I believe the hold-up was Bootstrap's default behavior to increase the `font-size` of `legend` by 1.5 https://github.com/blackbaud/skyux/blob/master/scss/Bootstrap/_forms.scss#L25

Visually, I'm assuming we'll want to change that behavior @Blackbaud-ToddRoberts?

**Current**

screen shot 2017-01-13 at 8 42 24 am

**Behavior if we use legend as is**

screen shot 2017-01-13 at 8 41 50 am

**Comment by Blackbaud-ToddRoberts** [comment]
I'd be inclined to leave the styling for <legend> how it is. If anyone happens to be using it in product I won't want to blow it up. Visually it seem ok here since the weight is less than the Demo heading.

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 1caef84aef921d084cbaaa922dbf1d0e934c8520
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/191715414

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 1caef84aef921d084cbaaa922dbf1d0e934c8520
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/191717850

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Review by Blackbaud-PatrickOFriel — APPROVED** [review]

**Pull request merged**
