### PR TITLE
bbAutonumeric filter changes

### PR DESCRIPTION
**Pull request by Blackbaud-MichaelLopez**
Allow bbAutonumeric filter to take a settings object

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: e191478fba6b03fc454170f0f9a500d77bba0a3a
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/117797542

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Just for consistency's sake throughout Sky, I'd rather use `angular.isString` and `angular.isObject` instead of $.type. But @Blackbaud-BobbyEarl and @Blackbaud-PaulCrowder might disagree. What do y'all think?

**Comment by Blackbaud-PaulCrowder** [comment]
I would change the code to just check for `angular.isObject()` and then perform the new behavior, then just have an else (no else if) that did what it did before.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: d4bcef0a57e0c72179eedef7f92f1fa7a67d37ef
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/117814091

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PaulCrowder** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/417/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Comment by Blackbaud-PaulCrowder** [comment]
Closes #418

**Pull request merged**
