### PR TITLE
Viewkeeper omnibar

### PR DESCRIPTION
**Pull request by Blackbaud-PatrickOFriel**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Since the ViewKeeper is not a documented component, should we provide the guidance of setting `bbViewKeeperConfig.hasOmnibar: false` somewhere?  Maybe actually document the ViewKeeper, or maybe just tuck it in with Grid?  

Perhaps it's worth having the ViewKeeper programmatically determine if the Omnibar is on the page?

**Comment by Blackbaud-PatrickOFriel** [comment]
Yeah I would say it's valuable to document `bbViewKeeperConfig` somewhere. Finding the right location will be interesting, because bbViewKeeper is more of an internal service. 

In terms of programmatically determining if viewkeeper is on the page, the tricky part is that the mediabreakpointhandler is kicked off in a `run` block, which may or may not occur after the omnibar is available in the page. Without significant rework of viewkeeper, I don't think it will be possible to detect omnibar programatically (unless I'm missing something in viewkeeper, I'm far from an expert on this module)

**Comment by Blackbaud-PatrickOFriel** [comment]
I think the correct way to handle this change is: keeping the hasOmnibar configuration option. Add documentation for viewkeeper configuration in bbGrid, since that's the location where consumers see the impact of viewkeeper. We can tie that work to #149. Agreed, @Blackbaud-BobbyEarl and @Blackbaud-PaulCrowder ?

**Comment by Blackbaud-BobbyEarl** [comment]
I like that idea @Blackbaud-PatrickOFriel .

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/629/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
