### PR TITLE
bb-phone-field Directive Minor Bug Fixes

### PR DESCRIPTION
**Pull request by Blackbaud-SeanLatif**
Fixing the following bugs we've experienced while implementing the bb-phone-field:
- 646944: If ng-model value is set upon load, the selected country should be set to that value's country
- 647279: US and UK were set as the preferredCountry and appearing at top of the flag dropdown. Now, the default country appears instead
- 647303: Only validate the input when the textbox is not prestine

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 27f8086bf24842037c96519259fb372f9e5cf417
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/143323692

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @Blackbaud-SeanLatif , is it correct to only validate phonefield if the value is not pristine? What if the form is preloaded with a invalid phone format? Does the form/backend just accept it?

**Comment by Blackbaud-SeanLatif** [comment]
@Blackbaud-PatrickOFriel : Yes to both. The team's logic behind that is that if users pre-load an invalid phone number (from RE7) and don't try to update it, then we shouldn't enforce validation on a value they weren't trying to update to begin with.

**Comment by Blackbaud-PatrickOFriel** [comment]
@Blackbaud-SeanLatif Okay, understood. Messing around with the new demo, if I set my ng-model to 2015555555 on initialization, and my country is USA, then I see that the actual input value is changed to (201) 555-5555 and the ng-model value is 2015555555. That doesn't seem consistent with how the control behaves not on initialization. Is this expected behavior?

**Comment by Blackbaud-SeanLatif** [comment]
@Blackbaud-PatrickOFriel I don't think that is the expected behavior. I'll look into how to fix that. Thanks for pointing it out!

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: a20f655e0007037492a856d92316fbab3a88f359
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/143438875

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-SeanLatif** [comment]
For story planning purposes:
Assuming this code is crisp, when can we expect it to be available?

**Comment by Blackbaud-PatrickOFriel** [comment]
I'll take a look at this tomorrow morning and we can have a release tomorrow or Thursday

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/678/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
