### PR TITLE
Definitionlist component

### PR DESCRIPTION
**Pull request by Blackbaud-CeciliaPrentice**

### CODE REVIEW

**Comment by Blackbaud-CeciliaPrentice** [comment]
@Blackbaud-BobbyEarl, do you have any feedback on this?

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-CeciliaPrentice in your discussions with @Blackbaud-ToddRoberts, did you nix having the definition lists floating next to each other?  

I see that happening in the [original design](https://github.com/blackbaud/skyux/issues/579) but not in yours.

**Comment by Blackbaud-ToddRoberts** [comment]
It needs to be doable, but it doesn't matter if it is built in to the component or if the teams has to put multiple instances in side by side containers.

**Comment by Blackbaud-BobbyEarl** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/685/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
