### PR TITLE
Fix search on grid context menu

### PR DESCRIPTION
**Pull request by Blackbaud-StacyCarlos**
Explicitly prevent search from applying to context menu items.

Issue is here #1047

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 354aa776b1e0f7087a84dd0ea9a639e437b93e05
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/255363004

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: d056d6344db3da03963f8c65bbc75c6ff814d896
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/255363036

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: dbc615e62b9b8b4b00bd605adaf6a2c772b0cffa
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/255418161

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-StacyCarlos** [comment]
@blackbaud-sky-savage retry

**Comment by Blackbaud-JaminQuimby** [comment]
@blackbaud-sky-savage retry

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: dbc615e62b9b8b4b00bd605adaf6a2c772b0cffa
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/255671475

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
hey @Blackbaud-StacyCarlos I'm going to check out what's going on with these visual test failures, something might have updated in browserstack or chrome/firefox to cause them, because they don't look related to your changes at all

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 9a8948c7013c5bf17267cfa132c786674a0e7597
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/255709059

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Review by Blackbaud-PatrickOFriel — APPROVED** [review]

**Pull request merged**
