### PR TITLE
Loadmore scrolltop

### PR DESCRIPTION
**Pull request by Blackbaud-PatrickOFriel**

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @blackbaud-johnly, could you take a look at the wording of this documentation. 

```
When the 'Load more' button is clicked, the event provides a promise that 
should be resolved with the set of new data to be appended to the grid.
```

Don't know if there's a better way to phrase that.

**Comment by blackbaud-johnly** [comment]
I think active voice would help (i.e., "users click " instead of "button is clicked"). I don't completely follow the chain of events in second half of the sentence (i.e., I can't tell if the button appends the data or if that is a separate action), but here's a rewrite strictly for active voice:

"When users click 'Load more,' the event provides a promise that the new data to append to the grid should resolve."

And here's a slightly longer variation that splits this into 2 short sentences.
"When users click 'Load more,' the event provides a promise. The new data to append to the grid should resolve that promise."

FWIW, I prefer the second version. I think it's easier to follow. ... Hopefully that helps, but please let me know if this doesn't work or if I can do anything else. Thanks.

**Comment by blackbaud-johnly** [comment]
Sorry. Realized after the first comment that "users click" should be "a user clicks" to avoid switching from plural to singular.

**Comment by Blackbaud-PatrickOFriel** [comment]
How about this 

```
When a user clicks the 'Load more' button, the event provides a promise. 
The consumer of the event should resolve the promise with the new data that
the grid appends to the existing data.
```

**Comment by blackbaud-johnly** [comment]
I think that's great.

**Pull request merged**
