### PR TITLE
Fix color of .label-success and .text-success 

### LINKED ISSUE #558: Fix color of "success" styles
In some places "success" status is using blue, but should use green.
Needs to be updated for .text-success and .label-success; alerts and toasts are correct.

### PR DESCRIPTION
**Pull request by josh-channin**
Fix #558 
.label-primary is still set to green per Todd

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
This will probably break screenshot tests. @Blackbaud-ToddRoberts, should we just remove the primary label, badge, and text from our screenshots since we don't encourage their use?

**Comment by Blackbaud-ToddRoberts** [comment]
I think we should leave them for now, and communicate to teams that it is explicitly not recommended first so they have time to update.

**Comment by Blackbaud-PatrickOFriel** [comment]
Looks like Savage wasn't kicked off @Blackbaud-BobbyEarl, any ideas why?

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by Blackbaud-BobbyEarl** [comment]
Sorry for the hold up guys.  Savage is being disconnected from GitHub on every request.  I'm looking into it and will report an update (and kick off your PR) once the issue has been resolved.

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 8699d39c5d3daa69a3271bdbc49bf481280b7435
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128451600

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b43b0ee504d52393a910437b0e70678f311359b4
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128861363

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 37640806606312b3d24780fb0cd9b8b1ebddb1c7
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128861368

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Looks like you need to update the badge screenshots too

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 945dcf468aa22200e92cc1504389253acd6bc1ff
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128861379

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 78b33a04885996b43fe8ebcc2ed218073e09ef6e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128861501

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 02b93373392c0b66e85661d9e41b0930ee4db4a9
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128881788

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: fa8bc6c6ee0f1ed24b69537ea03593b3628a7b31
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128881946

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/560/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
