### PR TITLE
Issue 276: Grid allow search restrictions

### PR DESCRIPTION
**Pull request by Blackbaud-SpencerMurphy**
This implements issue 276 by adding in a new property to the grids directive to restrict the properties that are searched by the checklist directive in the column chooser. I've added in tests to cover it, added in the proper documentation, and added this property to one of the demo grids.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: fbc1bf4dddc186ae592b66595dfcbf7c79d07094
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/109973913

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: fbc1bf4dddc186ae592b66595dfcbf7c79d07094
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/109999311

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
Apologies on the failures @Blackbaud-SpencerMurphy  Working through a few automation kinks.

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: fbc1bf4dddc186ae592b66595dfcbf7c79d07094
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/110004271

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
So we were discussing this change a bit further, and we think the correct solution to this issue is to search only by title and description when using the local search for the checklist control. The rationale for this is that users would be confused (like you saw in your situation) if they input a search term and some hidden field causes the list to be shortened, but nothing is highlighted like would usually happen.

So, I think the best solution to this issue is to change how local search works in the checklist control as a whole, because there will only ever be the title and description shown, never any other properties.

If you want to take on this change yourself, you can make the changes in this pull request, or I can take it on myself at the beginning of next week.

Thanks for the pull request, and sorry it took a bit for us to realize the solution we wanted!

**Comment by Blackbaud-PatrickOFriel** [comment]
Needs changes

**Comment by Blackbaud-PatrickOFriel** [comment]
Needs Changes

[Rejected with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/337/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Comment by Blackbaud-SpencerMurphy** [comment]
If the desired fix is to just fix checklist.js to only search on title and description, checklist.js would be the only file that would need to be changed (other than the spec and maybe the doc files for checklist) and none of my changes would be necessary anymore. Fixing checklist should be relatively easy to do. I'll see if I have time to take care of it this afternoon or tomorrow and let you know if I can't. As far as this pull request goes, it would honestly be easier to just start a new one from scratch since none of this code would be used.

**Comment by Blackbaud-PatrickOFriel** [comment]
Very true, then you can go ahead and close this, and just let me know if you want me to take care of it.

**Pull request closed without merging**
