### PR TITLE
Textexpand longtext overlaps parent

### PR DESCRIPTION
**Pull request by Blackbaud-MichaelLopez**
#498

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 914d512264684cfedde8376dd0298fc8b37dc10c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/123142439

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PaulCrowder** [comment]
There should be a visual regression test to go along with this since it's reproducible in Firefox and we run those tests in Firefox.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 97e360a05a7db68bf3abe39f03e3acfb6e828199
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/123227234

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/499/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
