### PR TITLE
bb-phone-field: Removing ng-model update

### PR DESCRIPTION
**Pull request by Blackbaud-SeanLatif**
Originally, when the ng-model for the bb-phone-field directive is loaded with an invalid number, it is automatically formatted if valid or blanked out of the textbox if invalid.

Because we want any and all text to be loaded to the bb-phone-field directive, we are removing this update. This way, "numbers" that were already invalid or unformatted will stay that way until they are intentionally edited or saved. Upon save, they will be validated and formatted accordingly, not before.

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 55ece5277430ee6833de70e29bec52fb87f78089
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/144852195

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
How is it a problem if you're only formatting when they are valid?

**Comment by Blackbaud-SeanLatif** [comment]
After looking at it further, the only real problem was that the textbox was only getting the value when it was valid. So you're right.

I'm reverting the change and moving the line that sets the textbox out of the "valid check" part so that we only format the ng-model if it is valid.

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b621541532df2167ccde8e5ea70a0923cfa50913
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/145024766

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-SeanLatif** [comment]
Is there any way to know which test failed in case it was me?

**Comment by Blackbaud-PatrickOFriel** [comment]
You can click on the build details link in the comment by savage. But I don't think it was you. We just have a bunch of builds happening right now and it overwhelmed browserstack. I'll kick it off again.

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b621541532df2167ccde8e5ea70a0923cfa50913
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/145032627

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
There should be a test related to this change before we merge it in

**Comment by Blackbaud-SeanLatif** [comment]
Aside from the one I added back in?

**Comment by Blackbaud-PatrickOFriel** [comment]
In the files changed I see no test that tests the changed logic in phonefield. Basically, I need a test for the case you are trying to fix with this change

**Comment by Blackbaud-SeanLatif** [comment]
Gotcha. On it now

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 93b864c5a5eb6bcdc3ede4464305f68097d7df04
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/145106868

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/701/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
