### PR TITLE
Accessibility tips for check, modal, popover components

### PR DESCRIPTION
**Pull request by Blackbaud-MattGregg**
Added short sections on using the components in accessible ways to their descriptions.

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: b8e0a8cd409927f1620f9c6f1536b0ad97d77d00
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/185584878

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 462ebb89659ba5c6a5e689c0c1f576f7923c205d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/185592793

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 462ebb89659ba5c6a5e689c0c1f576f7923c205d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/185599048

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 462ebb89659ba5c6a5e689c0c1f576f7923c205d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/185601405

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 462ebb89659ba5c6a5e689c0c1f576f7923c205d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/185605068

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 462ebb89659ba5c6a5e689c0c1f576f7923c205d
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/185609594

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Pull request merged**
