### PR TITLE
Fix color of .btn-success 

### PR DESCRIPTION
**Pull request by josh-channin**
#558

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: ab60487afc968b8ed13e5c7d3242fa2207d1a577
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/128875836

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 90012f4e3cada1c87a7950ee200dae09e57e1f86
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/129165548

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6b015977410f743ac48f99bd3b482339d658b018
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/129165554

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 41d9da3cd29b644cd0b68709d9169a8ad99ff579
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/129165558

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 58d91b705a92c269ac6b62e0fa901b919fdc4956
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/129165742

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @josh-channin, want to update the grid toolbar template file to have the add button use btn-primary instead of btn-success. I'm assuming we still want this to be blue, right @Blackbaud-ToddRoberts ?

**Comment by Blackbaud-ToddRoberts** [comment]
Yeah, it should be btn-primary

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 26f4517703f23300e0df4eb49f2952c47168541e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/129508376

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 26f4517703f23300e0df4eb49f2952c47168541e
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/129705303

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
One more fix @josh-channin, looks like in `grids/test/gridtoolbar.spec.js` on line 37, there's a reference to `btn-success` that needs to be changed to `btn-primary`

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 8e22760c8d7be7ffebd2d6b41c67e7ee2c2ebc70
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/129743997

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/564/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
