### PR TITLE
fix issue with vertical tabset group heading overlapping with chevron

### LINKED ISSUE #1075: Vertical tabset group header overlaps with chevron icon
### Expected behavior
When a vertical tabset group heading is long enough so that it would overlap with the chevron indicating that the group is open or closed, it should start wrapping.

### Actual behavior
The group heading text overlaps with the chevron icon before wrapping

### Steps to reproduce
Create a vertical tabset with a single group that has a rather long header. Then adjust your viewport size so that the header overlaps with the chevron icon.

### Plunker
http://plnkr.co/edit/nNT55oUYAw2rYMhnr8vs?p=preview

### PR DESCRIPTION
**Pull request by Blackbaud-BenCook**
Fixes #1075

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 6c8c40436ad0903924f2e0bee98426dd2d8c6077
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/280980783

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BenCook** [comment]
I'm not sure what the next steps are. I suspect the vertical tabset visual test failure was an expected/acceptable failure. Not sure why a few page summary visual tests failed.

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-BenCook... It does seem your changes would affect those two vertical tabset screenshots.  If that's the case, you should remove their baselines in your branch.  

As you also suggested, I would suggest the page summary failures are a fluke.  Hopefully re-running the tests (when you update your branch with the tabset screenshots removed) will cause them to pass.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: f5e3c4a76ee4755030cbc45bfc5c83fcd3de4fe3
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/287158351

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: f71997d72d9718f811f225c7d3dcf96fe3ed8b4c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/291693584

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: f71997d72d9718f811f225c7d3dcf96fe3ed8b4c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/291836271

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 7895d79a832466e7916477f0d9cf557d58fce0b1
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/293333997

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7895d79a832466e7916477f0d9cf557d58fce0b1
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/294837192

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Review by Blackbaud-BobbyEarl — APPROVED** [review]

**Pull request merged**
