### PR TITLE
Add bindings for setting active section and getting changes

### PR DESCRIPTION
**Pull request by Blackbaud-MatthewBell**
Updating sectioned form component to support setting the active section
index and being alerted to changes to the active section index.

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 640a8e6c0c483522f7da02fafa4c8f69ef797b52
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/211356297

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-BobbyEarl** [comment]
At first glance this failure appears to be unrelated to your changes @Blackbaud-MatthewBell.  Safari in BrowserStack seems to have not initialized correctly.  I'm going to kick the tests off again.

screen shot 2017-03-15 at 10 02 21 am

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 640a8e6c0c483522f7da02fafa4c8f69ef797b52
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/211361387

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Review by Blackbaud-PatrickOFriel — APPROVED** [review]

**Pull request merged**
