### PR TITLE
fix first checkbox in grid causes rows to shift 

### PR DESCRIPTION
**Pull request by josh-channin**
#576

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: 48490a36a34c1bd0490c66ffb491888e366586e0
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/131462054

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by josh-channin** [comment]
@Blackbaud-PatrickOFriel savage is saying - should match the baseline screenshot when the datepicker is appended to body and open - but I'm not seeing how the datepicker is affected.

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 10a36e71acc15ecc3faded59d08b76e02e1b690c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/131563543

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
So this prevents the shift, however, we do want that border with that color to exist EXCEPT on the border-top of the first jqgrid row.  So if you use this rule, then the desired behavior should occur 

```
.grid-multiselect {
        tr.ui-state-highlight {
            background-color: #eeeffb;
            border: 1px solid #dadbf6;

            &:nth-child(2) {
              border-top: none;
            }
        }
    }
```

We need to use nth-child(2) instead of nth-child(1) because jqgrid always has an invisible first row before the visible ones.

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 80189278145dfe330bd6208dbbb7cf89522536a1
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/133409802

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/577/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
