### PR TITLE
Skyux webpack nodist

### PR DESCRIPTION
**Pull request by Blackbaud-RobertTester**

### CODE REVIEW

**Comment by Blackbaud-PatrickOFriel** [comment]
@blackbaud-sky-savage retry

**Comment by Blackbaud-RobertTester** [comment]
Example of an application using skyux at build time https://github.com/Blackbaud-RobertTester/SkyUX-Webpack-Example

**Comment by Blackbaud-BobbyEarl** [comment]
@Blackbaud-RobertTester Follow these instructions to make yourself a public member of the Blackbaud organization.  Once you do that, we'll be able to kick off the request again.

https://help.github.com/articles/publicizing-or-hiding-organization-membership/

**Comment by Blackbaud-RobertTester** [comment]
Example of an application using SkyUX from CDN for a production deployment.  See the production webpack config.

**Comment by Blackbaud-RobertTester** [comment]
Membership has been updated

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: a5551ca2a4d639914fbabe2b9c399bcb30b23040
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/141706735

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-BobbyEarl** [comment]
Thanks @Blackbaud-RobertTester Looks like a small linting rule caught us.  You mind fixing the error called out in the Build details link above?

**Comment by Blackbaud-RobertTester** [comment]
Updated the require comment.  Lets see if everything passes now.

**Comment by Blackbaud-BobbyEarl** [comment]
@blackbaud-sky-savage retry

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 0125ce22adb24e4d5891c87d0ebf1074e996b904
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/141725590

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/666/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 0ea7e6e42e12245a441d02466c72d2283b41e199
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/143464399

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Pull request merged**
