### PR TITLE
Create a `reInitGrid` event listener that can be triggered to refresh…

### PR DESCRIPTION
**Pull request by Blackbaud-IanThomas**
… the grid manually from a controller #369

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 7e6e3b1306d883efd788702399b5e8f0d124857c
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/113138571

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Just a wording change in the documentation really, I would go with "The grid reinitializes itself when it receives this event"

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: fafec46905d8018cb0a66e8006a7c1bea51158e9
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/113148304

(_Please note that this is a [fully automated](https://github.com/twbs/savage) comment._)

**Comment by Blackbaud-PatrickOFriel** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/blackbaud/skyux/pull-request/370/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=blackbaud/skyux)

**Pull request merged**
