### PR TITLE
Modal dismiss improvement

### PR DESCRIPTION
**Pull request by Blackbaud-StacyCarlos**
Gives cancel and close buttons direct access to the dismiss functionality rather then using $parent.$parent.$dismiss syntax

### CODE REVIEW

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: b730b5aeb392a916d65e3eb1082f9508856cb254
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/266120065

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests failed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **BUSTED**

Commit: a31db12b21ab86746b8480e08ca5430d4e673298
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/266154782

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 61e3b72004d356b233095c7c87006b848abee333
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/266157169

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 604b335388db222d69e14a9ccb2d4da43f4aa711
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/278311427

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by blackbaud-sky-savage** [comment]
**Tests passed.** Automated cross-browser testing via BrowserStack and Travis CI shows that the JavaScript changes in this pull request are: **CONFIRMED**

Commit: 629b90ca10d09847aa1dac12a3a4843027282fa9
Build details: https://travis-ci.org/blackbaud-sky-savage/skyux/builds/278717388

(*Please note that this is a [fully automated](https://github.com/twbs/savage) comment.*)

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-StacyCarlos This looks good! Do you mind writing a unit test for this behavior?

**Comment by Blackbaud-StacyCarlos** [comment]
@Blackbaud-SteveBrush The functionality is already unit tested, I simply refactored the the way the functionality is called. The unit tests should for the normal modal dismiss should be enough unless you want me to test something more specifically.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-StacyCarlos I was thinking it'd be good to have a unit test that checked if `dismiss` existed on the controller, but it seems that the controller method is getting indirectly tested, here: https://github.com/blackbaud/skyux/pull/1065/files#diff-fe2b076a1fe5a79c54e0a7e9d42b6e39R1.

So, no worries. This looks good!

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
